### PR TITLE
Fix structured fuzzer

### PR DESCRIPTION
**Pull request by addisoncrump**
Partial fix for #28.

### CODE REVIEW

**Review by jasikpark — APPROVED** [review]
arbitrary :)

**Comment by kaleidawave** [comment]
Nice. (I am on the `wasm-test` issue, it's not related to fuzzing). Can see the structured error now it is compiling. This is good to merge now right?

**Comment by addisoncrump** [comment]
No further changes here -- fuzzer is working as intended :slightly_smiling_face: However, it seems there are other crash conditions, potentially.

**Comment by kaleidawave** [comment]
Awesome, yes when I have more time I can work on fixing up the parser.

**Pull request merged**
