### PR TITLE
Few parser fixes

### PR DESCRIPTION
**Pull request by kaleidawave**
- Fix capitalisation in `ForLoopStatementInitialiser`
- Fix for #154
- Fix for #161
- Fix for `parser/examples/code_blocks_to_script.rs` and `.github/workflows/performance-and-size.yml`
- Raise parse errors for *trailing* syntax in variable field currently not raising a parse error
- Add different array printing ([see comment below](https://github.com/kaleidawave/ezno/pull/158#issuecomment-2169621017))

### CODE REVIEW

**Comment by kaleidawave** [comment]
#### Pretty formating of array

Currently if some structures including array have check to see if their content printed on the same line overflows a specific count. This works well (see `parser/examples/pretty_printing.rs`). However in a project I am working on I had a case where I have a array of lots of literals.
```ts
const x = [1, 1, 0, 0, 1, 0, 1, ... *etc* ]
```
as it breaks the max-line width threshold it is pretty printed as
```ts
const x = [
  1, 
  1, 
  0, 
  0, 
  1, 
  0, 
  1,
   ... *etc* 
]
```
I wonder if in this case it could be alternatively done in half-way manner, where the items are distributed?
```ts
const x = [
  1, 1, 0, 0, ...
  1, 0, 1, 0, ...
   ... *etc* 
]
```

**Comment by kaleidawave** [comment]
Help @addisoncrump @jasikpark.  Not sure why it is now requiring `x86_64-unknown-linux-musl`, when the rest of the tests run on `x86_64-unknown-linux-gnu`?

```
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-unknown-linux-musl`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `libc` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
Error: failed to build fuzz script: RUSTFLAGS="-Cpasses=sancov-module -Cllvm-args=-sanitizer-coverage-level=4 -Cllvm-args=-sanitizer-coverage-inline-8bit-counters -Cllvm-args=-sanitizer-coverage-pc-table -Cllvm-args=-sanitizer-coverage-trace-compares --cfg fuzzing -Clink-dead-code -Cllvm-args=-sanitizer-coverage-stack-depth -Cdebug-assertions -C codegen-units=1" "cargo" "build" "--manifest-path" "/home/runner/work/ezno/ezno/parser/fuzz/Cargo.toml" "--target" "x86_64-unknown-linux-musl" "--release" "--config" "profile.release.debug=true" "--bin" "module_roundtrip_naive"
Error: Process completed with exit code 1.
```

It was working yesterday (maybe a change in 1.79 that has just come through, not sure though) and not sure whether changing the CI `dtolnay/rust-toolchain@stable` target is a good fix or would even work?

**Comment by addisoncrump** [comment]
You seem to have run into this: https://github.com/rust-fuzz/cargo-fuzz/issues/355

I'm surprised that hasn't already been fixed... I bumped the upstream issue.

**Comment by kaleidawave** [comment]
Need to look into this fuzzing issue before merge. Understand why broken, but not sure why now? There hasn't been an update to `cargo-fuzz` in a while? Manually setting the version hasn't seemed to work?

**Comment by kaleidawave** [comment]
Installing from the GitHub repository works? (`cargo install --git https://github.com/rust-fuzz/cargo-fuzz.git`). Only adds 18s to the action (to build the binary from source)? Should be okay, until https://github.com/rust-fuzz/cargo-fuzz/pull/365 is merged!

**Comment by lishaduck** [comment]
Are the issues linked resolved? You didn't put a colon after fix, so they didn't autoclose 😉

**Pull request merged**
